# fly.toml file for Python app

app = "MaatrCare"  # Use your app name, or Fly.io will generate one for you

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  # Use a custom Dockerfile for the Python app
  dockerfile = "./Dockerfile"

[env]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[[services]]
  http = true
  internal_port = 5001
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
